name: cable_list_tool
description: Offline cable list tool migrated from Python/PySide6 to Flutter.
publish_to: "none"

version: 2.0.0+200

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  archive: ^3.6.1
  excel: ^4.0.6
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: any
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
